spring:
 application:
  name: microservice1

server:
 port: 7004

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka
  instance:
    hostname: localhost

message:
  welcome to first microservice..!!
